module.exports = {
  //state
MY_CONTRACTS_LOADING: "MY_CONTRACTS_LOADING",
MY_CONTRACTS_LOADED: "MY_CONTRACTS_LOADED",
MY_CONTRACTS_NOT_LOADED: "MY_CONTRACTS_NOT_LOADED",
  //actions
MY_CONTRACTS_CHANGING_STATE: "MY_CONTRACTS_CHANGING_STATE"
}
