module.exports = {
  //state
NOT_WAITING_FOR_CONTRACT: "NOT_WAITING_FOR_CONTRACT",
WAITING_FOR_CONTRACT: "WAITING_FOR_CONTRACT",
MY_CONTRACTS_LOADING: "MY_CONTRACTS_LOADING",
MY_CONTRACTS_LOADED: "MY_CONTRACTS_LOADED",
MY_CONTRACTS_NOT_LOADED: "MY_CONTRACTS_NOT_LOADED",
  //actions
CONTRACT_MANIPULATION: "CONTRACT_MANIPULATION",
MY_CONTRACTS_CHANGING_STATE: "MY_CONTRACTS_CHANGING_STATE"
}
