module.exports = {
  //state//
POSSIBLE_CLIENT_CONTRACTS_LOADING: "POSSIBLE_CLIENT_CONTRACTS_LOADING",
POSSIBLE_CLIENT_CONTRACTS_LOADED: "POSSIBLE_CLIENT_CONTRACTS_LOADED",
POSSIBLE_CLIENT_CONTRACTS_NOT_LOADED: "POSSIBLE_CLIENT_CONTRACTS_NOT_LOADED",
  //actions
POSSIBLE_CLIENT_CONTRACTS_CHANGING_STATE: "POSSIBLE_CLIENT_CONTRACTS_CHANGING_STATE"
}
