module.exports = {
  //state
  POSSIBLE_CONTRACTS_LOADING: "POSSIBLE_CONTRACTS_LOADING",
  POSSIBLE_CONTRACTS_LOADED: "POSSIBLE_CONTRACTS_LOADED",
  POSSIBLE_CONTRACTS_NOT_LOADED: "POSSIBLE_CONTRACTS_NOT_LOADED",
  MY_PROVIDER_CONTRACTS_LOADING: "MY_PROVIDER_CONTRACTS_LOADING",
  MY_PROVIDER_CONTRACTS_LOADED: "MY_PROVIDER_CONTRACTS_LOADED",
  MY_PROVIDER_CONTRACTS_NOT_LOADED: "MY_PROVIDER_CONTRACTS_NOT_LOADED",

  //actions
  POSSIBLE_CONTRACTS_CHANGING_STATE: "POSSIBLE_CONTRACTS_CHANGING_STATE",
  MY_PROVIDER_CONTRACTS_CHANGING_STATE: "MY_PROVIDER_CONTRACTS_CHANGING_STATE"
}
